name: CMake Build

on: [pull_request, push]

jobs:
  build:
    name: ${{ matrix.os }} Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        build_type: [Release]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
      
    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
      
    - name: Configure CMake (Unix)
      if: matrix.os != 'windows-latest'
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
      
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}}
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      # Run tests if you have them
      run: ctest -C ${{matrix.build_type}} --output-on-failure
      continue-on-error: true
      
    - name: Upload Build Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.build_type }}
        path: |
          ${{github.workspace}}/build/zipit*
          ${{github.workspace}}/build/*.exe
        if-no-files-found: ignore