name: CMake Build

on: [pull_request, push]

jobs:
  build:
    name: ${{ matrix.os }} Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        project: [01-cmake-fetchcontent-zlib]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Print CMake Version
      run: cmake --version

    - name: Build CMake (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      working-directory: ${{github.workspace}}
      run: |
        cd ${{github.workspace}}/${matrix.project}
        cmake -E make_directory build
        cmake -S . -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        cmake --build build --config Release
        ctest -C ${{matrix.build_type}} --output-on-failure
      
    - name: Build CMake (Unix)
      if: matrix.os != 'windows-latest'
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        cd ${{github.workspace}}/${{ matrix.project }}
        cmake -E make_directory build
        cmake -S . -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        cmake --build build --config Release
        ctest -C ${{matrix.build_type}} --output-on-failure
