name: CMake Build

on: [pull_request, push]

jobs:
  build:
    name: ${{ matrix.os }} Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        build_type: [Release]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Print CMake Version
      run: cmake --version

    - name: Build CMake (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      working-directory: ${{github.workspace}}
      run: |
        cd ${{github.workspace}}/01-01-fetch-content-zlib
        cmake -E make_directory build
        cmake -S . -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        cmake --build build --config ${{matrix.build_type}}
        ctest -C ${{matrix.build_type}} --output-on-failure
      
    - name: Build CMake (Unix)
      if: matrix.os != 'windows-latest'
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        cd ${{github.workspace}}/01-01-fetch-content-zlib
        cmake -E make_directory build
        cmake -S . -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        cmake --build build --config ${{matrix.build_type}}
        ctest -C ${{matrix.build_type}} --output-on-failure
      
    #- name: Upload Build Artifacts
    #  if: always()
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: ${{ matrix.os }}-${{ matrix.build_type }}
    #    path: |
    #      ${{github.workspace}}/build/zipit*
    #      ${{github.workspace}}/build/*.exe
    #    if-no-files-found: ignore